#!/bin/sh
set -eu
exec python3 - "$@" <<'PY'
import argparse
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile


def version(program):
    if not shutil.which(program):
        raise RuntimeError(f"{program} is not installed")
    result = subprocess.run([program, "--version"], capture_output=True, text=True, timeout=5, check=True)
    match = re.search(r"\b(\d+)\.(\d+)\.(\d+)\b", result.stdout + result.stderr)
    if not match:
        raise RuntimeError(f"Cannot determine the installed {program} version")
    return tuple(int(part) for part in match.groups())


def source_role_property():
    candidates = []
    if os.environ.get("SPA_PLUGIN_DIR"):
        candidates.extend(Path(part) / "bluez5/libspa-bluez5.so" for part in os.environ["SPA_PLUGIN_DIR"].split(":"))
    if shutil.which("pkg-config"):
        result = subprocess.run(["pkg-config", "--variable=plugindir", "libspa-0.2"], capture_output=True, text=True, timeout=5)
        if result.returncode == 0 and result.stdout.strip():
            candidates.append(Path(result.stdout.strip()) / "bluez5/libspa-bluez5.so")
    for base in (Path("/usr/lib"), Path("/usr/lib64"), Path("/usr/local/lib")):
        candidates.append(base / "spa-0.2/bluez5/libspa-bluez5.so")
        candidates.extend(sorted(base.glob("*/spa-0.2/bluez5/libspa-bluez5.so")))
    for path in dict.fromkeys(candidates):
        if not path.is_file():
            continue
        data = path.read_bytes()
        # ตรวจ capability ของ plugin จริง เพราะชื่อ property เปลี่ยนใน PipeWire รุ่นใหม่
        for key in ("bluez5.media-source-role", "bluez5.a2dp-source-role"):
            if key.encode() + b"\0" in data:
                return key
        raise RuntimeError(f"The Bluetooth plugin {path} does not expose a supported phone-input property")
    raise RuntimeError("PipeWire's Bluetooth plugin was not found; install libspa-0.2-bluetooth first")


def install_policy(path, content, marker):
    if os.geteuid() == 0:
        raise RuntimeError("Install this policy as the desktop user, not root")
    if path.is_symlink():
        raise RuntimeError(f"Refusing to replace a symlink: {path}")
    if path.exists():
        if not path.is_file() or path.stat().st_uid != os.geteuid():
            raise RuntimeError(f"Refusing to replace a file not owned by this user: {path}")
        if not path.read_text().startswith(marker + " BT_AUDIO_BRIDGE_POLICY=1\n"):
            raise RuntimeError(f"Refusing to replace a policy not generated by BT Audio Bridge: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = None
    try:
        with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", dir=path.parent, prefix=".bt-audio-bridge-", delete=False) as output:
            temporary = Path(output.name)
            os.chmod(temporary, 0o600)
            output.write(content)
            output.flush()
            os.fsync(output.fileno())
        os.replace(temporary, path)
    finally:
        if temporary is not None and temporary.exists():
            temporary.unlink()


def main():
    parser = argparse.ArgumentParser(description="Preview a WirePlumber rule for only the selected iPhone. --install explicitly saves the rule; services are never restarted.")
    parser.add_argument("iphone_address", help="Paired iPhone Bluetooth address, AA:BB:CC:DD:EE:FF")
    parser.add_argument("--install", action="store_true", help="Explicitly install the previewed rule in the current user's WirePlumber configuration")
    args = parser.parse_args()
    address = args.iphone_address.upper()
    if not re.fullmatch(r"(?:[0-9A-F]{2}:){5}[0-9A-F]{2}", address):
        parser.error("iphone_address must have the form AA:BB:CC:DD:EE:FF")
    pw_version = version("pipewire")
    wp_version = version("wireplumber")
    if pw_version < (0, 3, 48):
        raise RuntimeError("PipeWire 0.3.48 or newer is required")
    if wp_version[0] != 0 or wp_version[1] not in (4, 5):
        raise RuntimeError("This generator supports WirePlumber 0.4 and 0.5; review the configuration format before using another version")
    role = source_role_property()
    config_home = Path(os.environ.get("XDG_CONFIG_HOME") or Path.home() / ".config")
    if not config_home.is_absolute():
        raise RuntimeError("XDG_CONFIG_HOME must be an absolute path")
    token = address.replace(":", "_")
    pw_text = ".".join(map(str, pw_version))
    wp_text = ".".join(map(str, wp_version))
    if wp_version[1] == 4:
        marker = "--"
        path = config_home / "wireplumber/bluetooth.lua.d/90-bt-audio-bridge-phone.lua"
        rule = f'''table.insert(bluez_monitor.rules, {{
  matches = {{
    {{ {{ "node.name", "matches", "bluez_input.{token}.*" }} }},
  }},
  apply_properties = {{
    ["{role}"] = "input",
    ["node.autoconnect"] = false,
    ["node.dont-reconnect"] = true,
    ["node.dont-fallback"] = true,
    ["node.hidden"] = true,
    ["priority.session"] = 0,
    ["bt-audio-bridge.phone"] = true,
  }},
}})
'''
    else:
        marker = "#"
        path = config_home / "wireplumber/wireplumber.conf.d/90-bt-audio-bridge-phone.conf"
        rule = f'''monitor.bluez.rules = [
  {{
    matches = [ {{ node.name = "~bluez_input\\\\.{token}\\\\..*" }} ]
    actions = {{
      update-props = {{
        {role} = "input"
        node.autoconnect = false
        node.dont-reconnect = true
        node.dont-fallback = true
        node.hidden = true
        priority.session = 0
        bt-audio-bridge.phone = true
      }}
    }}
  }}
]
'''
    content = f"{marker} BT_AUDIO_BRIDGE_POLICY=1\n{marker} BT_AUDIO_BRIDGE_PHONE={address}\n{marker} PipeWire {pw_text}; WirePlumber {wp_text}\n" + rule
    print(f"PipeWire {pw_text}, WirePlumber {wp_text}; input property: {role}", file=sys.stderr)
    print(f"Policy file: {path}", file=sys.stderr)
    if args.install:
        install_policy(path, content, marker)
        print(f"Installed {path}")
        print("Load the rule in your next desktop session, then connect the iPhone explicitly. No service was restarted.")
    else:
        print(content, end="")
        print("Preview only. Run again with --install after reviewing this rule to save it.", file=sys.stderr)


try:
    main()
except (OSError, RuntimeError, subprocess.SubprocessError) as error:
    print(f"phone-policy: {error}", file=sys.stderr)
    sys.exit(1)
PY
