#!/bin/sh
set -eu
exec python3 - "$@" <<'PY'
import argparse
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile


def version(program):
    if not shutil.which(program):
        raise RuntimeError(f"{program} is not installed")
    result = subprocess.run([program, "--version"], capture_output=True, text=True, timeout=5, check=True)
    match = re.search(r"\b(\d+)\.(\d+)\.(\d+)\b", result.stdout + result.stderr)
    if not match:
        raise RuntimeError(f"Cannot determine the installed {program} version")
    return tuple(int(part) for part in match.groups())


def install_policy(path, content, marker):
    if os.geteuid() == 0:
        raise RuntimeError("Install this policy as the desktop user, not root")
    if path.is_symlink():
        raise RuntimeError(f"Refusing to replace a symlink: {path}")
    if path.exists():
        if not path.is_file() or path.stat().st_uid != os.geteuid():
            raise RuntimeError(f"Refusing to replace a file not owned by this user: {path}")
        if not path.read_text().startswith(marker + " BLUETOOTH_AUDIO_BRIDGE_POLICY=1\n"):
            raise RuntimeError(f"Refusing to replace a policy not generated by Bluetooth Audio Bridge: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = None
    try:
        with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", dir=path.parent, prefix=".bluetooth-audio-bridge-", delete=False) as output:
            temporary = Path(output.name)
            os.chmod(temporary, 0o600)
            output.write(content)
            output.flush()
            os.fsync(output.fileno())
        os.replace(temporary, path)
    finally:
        if temporary is not None and temporary.exists():
            temporary.unlink()


def main():
    parser = argparse.ArgumentParser(description="Let the user service own the selected iPhone's direct playback route. --install saves the scoped rule; services are never restarted.")
    parser.add_argument("iphone_address", help="Paired iPhone Bluetooth address, AA:BB:CC:DD:EE:FF")
    parser.add_argument("--install", action="store_true", help="Explicitly install the previewed rule in the current user's WirePlumber configuration")
    args = parser.parse_args()
    address = args.iphone_address.upper()
    if not re.fullmatch(r"(?:[0-9A-F]{2}:){5}[0-9A-F]{2}", address):
        parser.error("iphone_address must have the form AA:BB:CC:DD:EE:FF")
    pw_version = version("pipewire")
    wp_version = version("wireplumber")
    if pw_version < (0, 3, 48):
        raise RuntimeError("PipeWire 0.3.48 or newer is required")
    if wp_version[0] != 0 or wp_version[1] not in (4, 5):
        raise RuntimeError("This generator supports WirePlumber 0.4 and 0.5; review the configuration format before using another version")
    config_home = Path(os.environ.get("XDG_CONFIG_HOME") or Path.home() / ".config")
    if not config_home.is_absolute():
        raise RuntimeError("XDG_CONFIG_HOME must be an absolute path")
    token = address.replace(":", "_")
    pw_text = ".".join(map(str, pw_version))
    wp_text = ".".join(map(str, wp_version))
    if wp_version[1] == 4:
        marker = "--"
        path = config_home / "wireplumber/bluetooth.lua.d/90-bluetooth-audio-bridge-phone.lua"
        rule = f'''table.insert(bluez_monitor.rules, {{
  matches = {{
    {{
      {{ "node.name", "matches", "bluez_input.{token}.*" }},
      {{ "api.bluez5.profile", "equals", "a2dp-source" }},
    }},
  }},
  apply_properties = {{
    ["node.autoconnect"] = false,
    ["node.dont-reconnect"] = true,
    ["node.dont-fallback"] = true,
    ["bluetooth-audio-bridge.phone"] = true,
    ["bluetooth-audio-bridge.mode"] = "direct",
  }},
}})
'''
    else:
        marker = "#"
        path = config_home / "wireplumber/wireplumber.conf.d/90-bluetooth-audio-bridge-phone.conf"
        rule = f'''monitor.bluez.rules = [
  {{
    matches = [ {{ node.name = "~bluez_input\\\\.{token}\\\\..*" api.bluez5.profile = "a2dp-source" }} ]
    actions = {{
      update-props = {{
        node.autoconnect = false
        node.dont-reconnect = true
        node.dont-fallback = true
        bluetooth-audio-bridge.phone = true
        bluetooth-audio-bridge.mode = "direct"
      }}
    }}
  }}
]
'''
    content = f"{marker} BLUETOOTH_AUDIO_BRIDGE_POLICY=1\n{marker} BLUETOOTH_AUDIO_BRIDGE_PHONE={address}\n{marker} BLUETOOTH_AUDIO_BRIDGE_ROUTE=direct\n{marker} PipeWire {pw_text}; WirePlumber {wp_text}\n" + rule
    print(f"PipeWire {pw_text}, WirePlumber {wp_text}; direct native playback", file=sys.stderr)
    print(f"Policy file: {path}", file=sys.stderr)
    if args.install:
        install_policy(path, content, marker)
        print(f"Installed {path}")
        print("Log out and back in to load the rule, then connect the iPhone explicitly and start bluetooth-audio-bridge.service.")
        print("After this rule is loaded, phone playback requires the running service. No service was restarted.")
    else:
        print(content, end="")
        print("Preview only. Run again with --install after reviewing this rule to save it.", file=sys.stderr)


try:
    main()
except (OSError, RuntimeError, subprocess.SubprocessError) as error:
    print(f"phone-policy: {error}", file=sys.stderr)
    sys.exit(1)
PY
